mp4_extends = '*.mp4'
gif_extends = '*.gif'
SIZE_MB = 1024*1024
FileFolder = '/home/venom/Videos/Demo_Video/'
#ThumbnailFileFolder = '/home/jason/Videos/Demo_Video/.thumbnail/'
title = 'GIS LED Web App'
ThumbnailFileFolder = '.thumbnail/'
flask_server_port = 9090
broadcast_port = 5000
scale_fit_ori_ratio = False
horizontal_display = False
default_width = 80
default_height = 96
init_config_file = ".pyqt5_led_player_config"