# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindows.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.StartHDMIin = QtWidgets.QPushButton(self.centralwidget)
        self.StartHDMIin.setGeometry(QtCore.QRect(580, 180, 111, 31))
        self.StartHDMIin.setCheckable(True)
        self.StartHDMIin.setChecked(True)
        self.StartHDMIin.setObjectName("StartHDMIin")
        self.videolabel = QtWidgets.QLabel(self.centralwidget)
        #self.videolabel.setGeometry(QtCore.QRect(10, 10, 321, 271))
        self.videolabel.setGeometry(QtCore.QRect(10, 10, 400, 500))
        self.videolabel.setObjectName("videolabel")
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setGeometry(QtCore.QRect(580, 280, 111, 31))
        self.closeButton.setCheckable(True)
        self.closeButton.setChecked(True)
        self.closeButton.setObjectName("closeButton")
        self.PauseButton = QtWidgets.QPushButton(self.centralwidget)
        self.PauseButton.setGeometry(QtCore.QRect(580, 230, 111, 31))
        self.PauseButton.setCheckable(True)
        self.PauseButton.setChecked(True)
        self.PauseButton.setObjectName("PauseButton")
        self.filelistWidget = QtWidgets.QListWidget(self.centralwidget)
        self.filelistWidget.setGeometry(QtCore.QRect(310, 90, 256, 371))
        self.filelistWidget.setObjectName("filelistWidget")
        self.playingfilelabel = QtWidgets.QLabel(self.centralwidget)
        self.playingfilelabel.setGeometry(QtCore.QRect(310, 40, 261, 31))
        self.playingfilelabel.setObjectName("playingfilelabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.StartHDMIin.setText(_translate("MainWindow", "Play All Repeat"))
        self.videolabel.setText(_translate("MainWindow", "VideoLabel"))
        self.closeButton.setText(_translate("MainWindow", "Close"))
        self.PauseButton.setText(_translate("MainWindow", "Pause"))
        self.playingfilelabel.setText(_translate("MainWindow", "Now Playing :"))
